name: ci-workflow-golang
on: 
  pull_request:
    branches:
      - develop
jobs: 
  check-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go actions/setup-go@v2
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test
        run: go test
      - name: Run
      - run: go run math.go